### ISSUE TITLE
Account Page Cleanup - Login Screen

### ISSUE THREAD

**Issue by tylernford** [lindseybradford/citizenry#152]
**Ticket**
https://app.asana.com/0/705583933956418/705583933956407

**Branch**
`login-screen`

**Theme**
`login-screen`

**Comment by lindseybradford** [comment]
Thanks for the thorough notes! 😻

**Comment by lindseybradford** [comment]
@tylernford  - Is this one a wrap?

**Comment by tylernford** [comment]
@lindseybradford Yes, just got confirmation yesterday which was too late for your merge.

I've added a `merge` that I'll start using when my tasks are ready to go so nothing slips through the cracks.

**Comment by lindseybradford** [comment]
@tylernford - No problem. Dig the labels!
