### ISSUE TITLE
Indonesia LP Updates

### ISSUE THREAD

**Issue by tylernford** [lindseybradford/citizenry#159]
**Ticket**
[Indonesia LP Updates](https://app.asana.com/0/715689288326778/731378122275706)

**Branch**
`indo-lp-updates`

**Theme**
`indo-lp-updates`

**Files**
`snippets/Country_Landing_Hero_Layout.liquid`
`assets/collection-landing-hero-layout.scss.liquid`
`snippets/Country_Landing_Hero_Scripts.liquid`

**Notes**
🤷‍♂️

**Comment by lindseybradford** [comment]
@tylernford  -  Good work! 💯
