### ISSUE TITLE
Checkout Updates

### ISSUE THREAD

**Issue by tylernford** [lindseybradford/citizenry#166]
**Ticket**
[Minor Checkout Updates](https://app.asana.com/0/734407927231242/741975414907823)

**Branch**
`checkout-updates`

**Theme**
`Checkout Updates`

**Files**
:construction:
`assets/checkout.scss.liquid`

**Notes**
:speak_no_evil:

**Comment by lindseybradford** [comment]
@tylernford  - Chipping in here: worked out why the summary was hiding and have a fix for that which I'll push later today. Not sure what's up with the map. Noticed that there's a console error for unexpected input coming from a cookieBot file, uc.js?bla-bla-bla.

**Comment by tylernford** [comment]
@lindseybradford I _just_ got there myself so you've saved me from doing any actual work :satisfied: Thanks!

**Comment by lindseybradford** [comment]
Related: https://github.com/lindseybradford/citizenry/commit/7905afac3e01e9b093c921d18875c656aef1792d#commitcomment-29892438
