### ISSUE TITLE
AOC Highlight Bug

### ISSUE THREAD

**Issue by lindseybradford** [lindseybradford/citizenry#304]
@tylernford - Just fyi, this should fix this 'bug':

Add this class: 

```
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}
```

…to images or whatever elements they don't want the user to be able to highlight with the cursor. Hope that helps. It's confusing that CZ refers to this as a bug so I wanted to clarify.

**Comment by tylernford** [comment]
🙌

**Comment by lindseybradford** [comment]
@tylernford  - I think we can close this one, right?

**Comment by tylernford** [comment]
@lindseybradford Hey! I was about to push an update here but... Setting _user-select: none_ on the image getting highlighted works, obviously, but Safari/Chrome just highlight the next element. All the way down the page. So we can disable selecting on the entire page or...

**Comment by lindseybradford** [comment]
LOL, innnnteresting. Ok, we shall say nope then (I can pass along your findings).
Thanks!
